import type { Metadata } from "next";
import { Geist_Mono } from "next/font/google";
import "./globals.css";
import CartProvider from "@/providers/cart-context";
import Navbar from "@/components/navbar";

const geistMono = Geist_Mono({
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistMono.className} antialiased`}>
        <CartProvider>
          <Navbar />
          {children}
        </CartProvider>
      </body>
    </html>
  );
}