import type { Metadata } from "next";
import { Geist_Mono } from "next/font/google";
import "./globals.css";
import CartProvider from "@/providers/cart-context";
import Navbar from "@/components/navbar";
import { Toaster } from "@/components/ui/sonner";

const geistMono = Geist_Mono({
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistMono.className} antialiased`}>
        <CartProvider>
          <div className="flex min-h-screen flex-col">
            <Navbar />
            <main className="flex-1">{children}</main>
          </div>
          <Toaster />
        </CartProvider>
      </body>
    </html>
  );
}